FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY .. .
CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8001"]